version: "3"
services:
  db:
    image: postgres:12
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  backend:
    build: ./server
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    entrypoint: ["/bin/sh", "/usr/src/app/startup.sh"]
    volumes:
      - ./server:/usr/src/app
    command: npm run dev

  frontend:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/usr/src/app
    command: npm start

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  postgres_data:
