version: "3"
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: CatMaster
      POSTGRES_PASSWORD: miaou12
      POSTGRES_DB: dbpaw
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  backend:
    build: ./server
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://CatMaster:miaou12@db:5432/dbpaw
    volumes:
      - ./server:/usr/src/app
    command: npm run dev

  frontend:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/usr/src/app
    command: npm start

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  postgres_data:
